import type { Story } from '../types';

// Eight short chapters retold for young listeners (about 5-10 minutes with activities).
export const ODYSSEY: Story = {
  id: 'odyssey',
  title: 'The Journey of Odysseus',
  titleKo: '오디세우스의 모험',
  summaryKo: '트로이 목마부터 키클롭스, 세이렌까지. 집으로 돌아가는 영리한 왕의 이야기를 들어 봐요.',
  levelKo: '중급',
  ageKo: '초등 고학년 이상',
  sourceKo: '호메로스 『오디세이아』를 쉽게 다시 쓴 이야기',
  handsOnKo: '이야기 중간에 직접 배를 띄우고, 목마를 끌고, 활을 당겨요!',
  cover: { chapterId: 'ithaca', beats: [0, 1, 2, 3, 4] },
  narration: 'recorded',
  chapters: [
    {
      id: 'ithaca',
      title: 'The King of Ithaca',
      titleKo: '이타카의 왕',
      sentences: [
        { beat: 0, en: 'Long ago, a clever king named Odysseus lived on a small island called Ithaca.', ko: '옛날 옛적, 오디세우스라는 영리한 왕이 이타카라는 작은 섬에 살았어요.' },
        { beat: 1, en: 'He loved his wife, Penelope, and their baby son, Telemachus.', ko: '그는 아내 페넬로페와 아기 아들 텔레마코스를 무척 사랑했어요.' },
        { beat: 2, en: 'One day, a ship came with bad news: there was a great war in Troy.', ko: '어느 날, 배 한 척이 나쁜 소식을 가져왔어요. 트로이에서 큰 전쟁이 일어났다는 거예요.' },
        { beat: 3, en: 'Odysseus had to join the war, so he said goodbye to his family.', ko: '오디세우스는 전쟁에 나가야 했고, 그래서 가족에게 작별 인사를 했어요.' },
        { beat: 4, en: '"I will come back," he promised, and his ship sailed away.', ko: '"꼭 돌아올게." 그는 약속했고, 그의 배는 멀리 떠나갔어요.', bubble: { speaker: 'Odysseus', text: 'I will come back!' }, action: { kind: 'tap', target: 'ship', promptEn: 'Tap the ship to set sail!', promptKo: '배를 눌러 출항시켜요!' } },
      ],
      words: [
        { word: 'island', ko: '섬', hotspot: 'island', beat: 0 },
        { word: 'king', ko: '왕', hotspot: 'hero', beat: 1 },
        { word: 'ship', ko: '배', hotspot: 'ship', beat: 2 },
        { word: 'promise', ko: '약속하다', hotspot: 'hero', beat: 4 },
      ],
      quiz: {
        question: 'Why did Odysseus leave Ithaca?',
        questionKo: '오디세우스는 왜 이타카를 떠났나요?',
        options: ['To join a war in Troy', 'To find a new home', 'To go fishing'],
        answer: 0,
        evidence: 3,
        explainKo: '배가 트로이 전쟁 소식을 가져왔고, 오디세우스는 전쟁(war)에 나가야 했어요.',
      },
    },
    {
      id: 'horse',
      title: 'The Wooden Horse',
      titleKo: '트로이 목마',
      sentences: [
        { beat: 0, en: 'For ten long years, the Greeks fought against the city of Troy.', ko: '10년이라는 긴 세월 동안, 그리스 사람들은 트로이라는 도시와 싸웠어요.' },
        { beat: 0, en: 'But the walls of Troy were too tall and too strong.', ko: '하지만 트로이의 성벽은 너무 높고 튼튼했어요.' },
        { beat: 1, en: 'Then Odysseus had a clever idea: "Let\'s build a giant wooden horse!"', ko: '그때 오디세우스에게 영리한 생각이 떠올랐어요. "커다란 나무 말을 만들자!"', bubble: { speaker: 'Odysseus', text: "Let's build a horse!" } },
        { beat: 2, en: 'The bravest soldiers hid inside the horse, and the other Greeks sailed away.', ko: '가장 용감한 병사들이 말 안에 숨었고, 나머지 그리스 사람들은 배를 타고 떠났어요.' },
        { beat: 3, en: 'The Trojans thought it was a gift, so they pulled it into their city.', ko: '트로이 사람들은 그것이 선물이라고 생각해서, 도시 안으로 끌고 들어갔어요.', action: { kind: 'tap', target: 'horse', count: 3, promptEn: 'Pull the horse! Tap it three times.', promptKo: '말을 세 번 눌러 성 안으로 끌어요!' } },
        { beat: 4, en: 'That night, the soldiers climbed out and opened the gates. Troy had fallen!', ko: '그날 밤, 병사들이 몰래 나와 성문을 열었어요. 트로이가 무너졌어요!' },
      ],
      words: [
        { word: 'wall', ko: '성벽', hotspot: 'walls', beat: 0 },
        { word: 'horse', ko: '말', hotspot: 'horse', beat: 1 },
        { word: 'soldier', ko: '병사', hotspot: 'soldiers', beat: 2 },
        { word: 'gate', ko: '성문', hotspot: 'gate', beat: 4 },
      ],
      quiz: {
        question: 'Why did the Trojans pull the horse into their city?',
        questionKo: '트로이 사람들은 왜 목마를 도시 안으로 끌고 갔나요?',
        options: ['They wanted to ride it', 'They thought it was a gift', 'Odysseus asked them to'],
        answer: 1,
        evidence: 4,
        explainKo: '트로이 사람들은 목마를 선물(gift)이라고 생각했어요. 그 안에 병사들이 숨어 있는 줄 몰랐죠.',
      },
    },
    {
      id: 'cave',
      title: "The Cyclops' Cave",
      titleKo: '키클롭스의 동굴',
      sentences: [
        { beat: 0, en: 'On the way home, Odysseus and his men found a big cave.', ko: '집으로 돌아가는 길에, 오디세우스와 부하들은 커다란 동굴을 발견했어요.' },
        { beat: 1, en: 'Inside, there was a lot of cheese and milk, so they started to eat.', ko: '안에는 치즈와 우유가 가득했고, 그래서 그들은 먹기 시작했어요.', action: { kind: 'tap', target: 'cave', promptEn: 'Tap the cave to look inside.', promptKo: '동굴을 눌러 안을 들여다봐요.' } },
        { beat: 2, en: 'Suddenly, the ground shook. A giant with only one eye came in with his sheep.', ko: '갑자기 땅이 흔들렸어요. 눈이 하나뿐인 거인이 양들과 함께 들어왔어요.' },
        { beat: 3, en: 'He was Polyphemus the Cyclops, and he rolled a huge rock across the door.', ko: '그는 키클롭스 폴리페모스였고, 커다란 바위를 굴려 입구를 막아 버렸어요.' },
        { beat: 4, en: '"Who are you?" the giant roared.', ko: '"너는 누구냐?" 거인이 으르렁거렸어요.', bubble: { speaker: 'Cyclops', text: 'Who are you?' } },
        { beat: 5, en: 'Odysseus smiled and said, "My name is Nobody."', ko: '오디세우스는 미소 지으며 말했어요. "내 이름은 아무도 아니야."', bubble: { speaker: 'Odysseus', text: 'My name is Nobody.' } },
      ],
      words: [
        { word: 'cave', ko: '동굴', hotspot: 'cave', beat: 0 },
        { word: 'giant', ko: '거인', hotspot: 'cyclops', beat: 2 },
        { word: 'sheep', ko: '양', hotspot: 'sheep', beat: 2 },
        { word: 'rock', ko: '바위', hotspot: 'rock', beat: 3 },
      ],
      quiz: {
        question: 'What did Odysseus say his name was?',
        questionKo: '오디세우스는 자기 이름을 뭐라고 말했나요?',
        options: ['Polyphemus', 'Troy', 'Nobody'],
        answer: 2,
        evidence: 5,
        explainKo: '오디세우스는 "Nobody(아무도 아닌 사람)"라고 가짜 이름을 댔어요. 이 꾀가 다음 장면에서 중요해져요!',
      },
    },
    {
      id: 'nobody',
      title: "Nobody's Trick",
      titleKo: '"아무도 아니야"의 꾀',
      sentences: [
        { beat: 0, en: 'Odysseus gave the giant a big bowl of strong, sweet wine.', ko: '오디세우스는 거인에게 독하고 달콤한 포도주를 한 사발 주었어요.' },
        { beat: 1, en: 'The Cyclops drank it all and fell into a deep sleep.', ko: '키클롭스는 그것을 다 마시고 깊은 잠에 빠졌어요.' },
        { beat: 2, en: 'Then the men used a long, sharp stick to hurt his one big eye.', ko: '그러자 부하들은 길고 뾰족한 막대로 거인의 하나뿐인 큰 눈을 공격했어요.' },
        { beat: 3, en: '"Help! Nobody is hurting me!" he shouted, but no one came to help.', ko: '"도와줘! 아무도 아닌 자가 날 다치게 해!" 그가 외쳤지만, 아무도 도우러 오지 않았어요.', bubble: { speaker: 'Cyclops', text: 'Nobody is hurting me!' } },
        { beat: 4, en: 'In the morning, the men held on under the sheep and escaped from the cave.', ko: '아침이 되자, 부하들은 양의 배 밑에 매달려 동굴을 빠져나갔어요.', action: { kind: 'tap', target: 'sheep', promptEn: 'Tap the sheep to escape!', promptKo: '양을 눌러 함께 탈출해요!' } },
      ],
      words: [
        { word: 'wine', ko: '포도주', hotspot: 'wine', beat: 0 },
        { word: 'sleep', ko: '잠, 자다', hotspot: 'cyclops', beat: 1 },
        { word: 'stick', ko: '막대기', hotspot: 'stick', beat: 2 },
        { word: 'escape', ko: '탈출하다', hotspot: 'sheep', beat: 4 },
      ],
      quiz: {
        question: "Why didn't anyone come to help the Cyclops?",
        questionKo: '왜 아무도 키클롭스를 도우러 오지 않았나요?',
        options: ['His friends were sleeping', 'He shouted that "Nobody" was hurting him', 'The cave was too far away'],
        answer: 1,
        evidence: 3,
        explainKo: '거인이 "Nobody(아무도 없다)가 날 다치게 해!"라고 외쳐서, 다른 거인들은 아무 일도 없다고 생각했어요.',
      },
    },
    {
      id: 'winds',
      title: 'The Bag of Winds',
      titleKo: '바람 자루',
      sentences: [
        { beat: 0, en: 'Next, the King of the Winds gave Odysseus a special bag.', ko: '다음으로, 바람의 왕이 오디세우스에게 특별한 자루를 주었어요.' },
        { beat: 0, en: '"All the strong winds are inside. Never open it!" he said.', ko: '"거센 바람이 모두 이 안에 들어 있다. 절대 열지 마라!" 그가 말했어요.', bubble: { speaker: 'King of the Winds', text: 'Never open it!' } },
        { beat: 1, en: 'They sailed for nine days, and soon they could see Ithaca.', ko: '그들은 아흐레 동안 항해했고, 곧 이타카가 보이기 시작했어요.' },
        { beat: 2, en: 'But the sailors thought the bag was full of gold, so they opened it.', ko: '하지만 선원들은 자루에 금이 가득하다고 생각해서 그것을 열어 버렸어요.' },
        { beat: 3, en: 'Whoosh! The winds rushed out and blew the ship far, far away.', ko: '휘이익! 바람이 쏟아져 나와 배를 아주 멀리 날려 보냈어요.', action: { kind: 'tap', target: 'bag', promptEn: 'What is inside? Tap the bag!', promptKo: '자루 안에 뭐가 있을까요? 자루를 눌러요!' } },
      ],
      words: [
        { word: 'bag', ko: '자루, 가방', hotspot: 'bag', beat: 0 },
        { word: 'sailor', ko: '선원', hotspot: 'sailors', beat: 2 },
        { word: 'gold', ko: '금', hotspot: 'bag', beat: 2 },
        { word: 'wind', ko: '바람', hotspot: 'winds', beat: 3 },
      ],
      quiz: {
        question: 'Why did the sailors open the bag?',
        questionKo: '선원들은 왜 자루를 열었나요?',
        options: ['They thought there was gold inside', 'They wanted to see Ithaca', 'The king told them to'],
        answer: 0,
        evidence: 3,
        explainKo: '선원들은 자루 안에 금(gold)이 있다고 오해했어요. 그래서 왕의 경고를 어기고 말았죠.',
      },
    },
    {
      id: 'circe',
      title: "Circe's Magic",
      titleKo: '마녀 키르케',
      sentences: [
        { beat: 0, en: 'The ship came to an island where a witch named Circe lived.', ko: '배는 키르케라는 마녀가 사는 섬에 도착했어요.' },
        { beat: 1, en: 'She gave the men a magic drink, and poof! They turned into pigs.', ko: '그녀가 부하들에게 마법의 음료를 주자, 펑! 그들은 돼지로 변했어요.' },
        { beat: 2, en: 'A kind god gave Odysseus a special flower to keep him safe.', ko: '친절한 신이 오디세우스를 지켜 줄 특별한 꽃을 주었어요.' },
        { beat: 3, en: '"Why doesn\'t my magic work?" Circe cried in surprise.', ko: '"왜 내 마법이 통하지 않지?" 키르케가 깜짝 놀라 외쳤어요.', bubble: { speaker: 'Circe', text: "My magic doesn't work!" } },
        { beat: 4, en: 'Odysseus asked her to turn the pigs back into men, and she did.', ko: '오디세우스가 돼지들을 다시 사람으로 돌려 달라고 하자, 그녀는 그렇게 해 주었어요.', action: { kind: 'tap', target: 'pigs', count: 2, promptEn: 'Tap the pigs to break the magic!', promptKo: '돼지들을 두 번 눌러 마법을 풀어요!' } },
      ],
      words: [
        { word: 'witch', ko: '마녀', hotspot: 'circe', beat: 0 },
        { word: 'magic', ko: '마법', hotspot: 'circe', beat: 1 },
        { word: 'pig', ko: '돼지', hotspot: 'pigs', beat: 1 },
        { word: 'flower', ko: '꽃', hotspot: 'flower', beat: 2 },
      ],
      quiz: {
        question: "Why didn't Circe's magic work on Odysseus?",
        questionKo: '키르케의 마법은 왜 오디세우스에게 통하지 않았나요?',
        options: ['He did not drink anything', 'He was already a pig', 'He had a special flower'],
        answer: 2,
        evidence: 2,
        explainKo: '신이 준 특별한 꽃(flower)이 오디세우스를 마법으로부터 지켜 주었어요.',
      },
    },
    {
      id: 'sirens',
      title: 'The Song of the Sirens',
      titleKo: '세이렌의 노래',
      sentences: [
        { beat: 0, en: 'Soon the ship had to sail past the Sirens.', ko: '곧 배는 세이렌 곁을 지나가야 했어요.' },
        { beat: 0, en: 'Their songs were so beautiful that sailors forgot everything and crashed into the rocks.', ko: '그들의 노래는 너무 아름다워서 선원들은 모든 것을 잊고 바위에 부딪히곤 했어요.' },
        { beat: 1, en: "Odysseus put soft wax in his sailors' ears, so they could not hear.", ko: '오디세우스는 선원들이 듣지 못하도록 귀에 부드러운 밀랍을 넣었어요.', action: { kind: 'tap', target: 'sailors', promptEn: 'Tap a sailor to put wax in his ears.', promptKo: '선원을 눌러 귀를 막아 줘요!' } },
        { beat: 2, en: 'But he wanted to hear the song, so he asked them to tie him to the mast.', ko: '하지만 그는 노래를 듣고 싶어서, 자신을 돛대에 묶어 달라고 했어요.' },
        { beat: 3, en: 'When the Sirens sang, he shouted, "Let me go!" but the sailors kept rowing.', ko: '세이렌이 노래하자 그는 "날 풀어 줘!"라고 외쳤지만, 선원들은 계속 노를 저었어요.', bubble: { speaker: 'Odysseus', text: 'Let me go!' } },
        { beat: 4, en: 'At last, the ship passed the Sirens safely.', ko: '마침내 배는 세이렌을 무사히 지나갔어요.' },
      ],
      words: [
        { word: 'song', ko: '노래', hotspot: 'sirens', beat: 0 },
        { word: 'wax', ko: '밀랍', hotspot: 'sailors', beat: 1 },
        { word: 'mast', ko: '돛대', hotspot: 'mast', beat: 2 },
        { word: 'tie', ko: '묶다', hotspot: 'mast', beat: 2 },
      ],
      quiz: {
        question: 'Why did Odysseus ask the sailors to tie him to the mast?',
        questionKo: '오디세우스는 왜 선원들에게 자신을 돛대에 묶어 달라고 했나요?',
        options: ['He was very tired', 'He wanted to hear the song safely', 'He wanted to swim to the Sirens'],
        answer: 1,
        evidence: 3,
        explainKo: '노래는 듣고 싶었지만 바위로 끌려가면 안 되니까, 몸을 돛대에 묶어 달라고 한 거예요.',
      },
    },
    {
      id: 'home',
      title: 'Home at Last',
      titleKo: '마침내 집으로',
      sentences: [
        { beat: 0, en: 'After twenty years, Odysseus finally came home to Ithaca.', ko: '20년 만에, 오디세우스는 마침내 이타카로 돌아왔어요.' },
        { beat: 0, en: 'He dressed as an old beggar, so no one knew who he was.', ko: '그는 늙은 거지로 변장해서, 아무도 그를 알아보지 못했어요.' },
        { beat: 1, en: 'Many proud men wanted to marry Penelope and take the palace.', ko: '거만한 남자들이 페넬로페와 결혼해서 궁전을 차지하려고 했어요.' },
        { beat: 2, en: 'Penelope brought out Odysseus\'s old bow. "Who can shoot through twelve axes?"', ko: '페넬로페는 오디세우스의 오래된 활을 가져왔어요. "누가 도끼 열두 개를 꿰뚫어 쏠 수 있나요?"', bubble: { speaker: 'Penelope', text: 'Who can shoot through twelve axes?' } },
        { beat: 3, en: 'No one could even bend the bow, except the old beggar. His arrow flew through all twelve axes!', ko: '아무도 그 활을 구부리지도 못했어요. 늙은 거지만 빼고요. 그의 화살은 도끼 열두 개를 모두 꿰뚫었어요!', action: { kind: 'hold', target: 'bow', promptEn: 'Press and hold the bow to pull the string!', promptKo: '활을 길게 눌러 시위를 당겨요!' } },
        { beat: 4, en: '"I am Odysseus!" he said, and his family was together again at last.', ko: '"내가 오디세우스요!" 그가 말했고, 가족은 마침내 다시 함께하게 되었어요.', bubble: { speaker: 'Odysseus', text: 'I am Odysseus!' } },
      ],
      words: [
        { word: 'beggar', ko: '거지', hotspot: 'hero', beat: 0 },
        { word: 'palace', ko: '궁전', hotspot: 'palace', beat: 1 },
        { word: 'bow', ko: '활', hotspot: 'bow', beat: 2 },
        { word: 'arrow', ko: '화살', hotspot: 'arrow', beat: 3 },
      ],
      quiz: {
        question: 'How did everyone learn that the beggar was Odysseus?',
        questionKo: '사람들은 거지가 오디세우스라는 걸 어떻게 알게 되었나요?',
        options: ['Only he could use the old bow', 'He showed everyone his crown', 'Penelope saw his ship'],
        answer: 0,
        evidence: 4,
        explainKo: '오디세우스의 활을 다룰 수 있는 사람은 오디세우스 자신뿐이었어요. 그래서 진짜 왕이라는 게 밝혀졌죠.',
      },
    },
  ],
};
