import type { FeelingChoice, Story } from '../types';

/*
 * Kenneth Grahame, "The Reluctant Dragon" (Dream Days, 1898), retold in easy
 * English for young learners. The original events, characters and ending are
 * kept; sentences and wording are new. Ten chapters, about 1,450 words, so the
 * narration alone is roughly ten minutes at a gentle storytelling pace.
 */

const SHY: FeelingChoice = { en: 'Shy', ko: '수줍어요', face: '😊' };
const ANGRY: FeelingChoice = { en: 'Angry', ko: '화나요', face: '😠' };
const SLEEPY: FeelingChoice = { en: 'Sleepy', ko: '졸려요', face: '😴' };
const WORRIED: FeelingChoice = { en: 'Worried', ko: '걱정돼요', face: '😟' };
const EXCITED: FeelingChoice = { en: 'Excited', ko: '신나요', face: '🤩' };

export const RELUCTANT_DRAGON: Story = {
  id: 'reluctant-dragon',
  title: 'The Reluctant Dragon',
  titleKo: '싸우기 싫은 용',
  summaryKo: '언덕 위 동굴에 용이 나타났어요. 그런데 이 용은 싸움보다 시와 노을을 좋아해요! 용과 친구가 된 소년은 용을 물리치러 온 기사와 함께 아무도 다치지 않는 방법을 찾아요.',
  levelKo: '초급',
  ageKo: '초등 저학년부터',
  sourceKo: '케네스 그레이엄 「The Reluctant Dragon」(『Dream Days』, 1898)을 쉬운 영어로 다시 쓴 이야기',
  handsOnKo: '숨은 용을 찾고, 반짝반짝 비늘을 닦아 주고, 용의 마음도 골라 봐요!',
  cover: { chapterId: 'hill', beats: [1, 2, 3, 4, 5] },
  narration: 'recorded',
  chapters: [
    {
      id: 'cottage',
      title: 'Only a Dragon',
      titleKo: '그냥 용일 뿐이에요',
      sentences: [
        { beat: 0, en: 'Long ago, a shepherd lived in a little cottage below a big green hill.', ko: '옛날 옛적, 한 양치기가 커다란 초록 언덕 아래 작은 오두막에 살았어요.' },
        { beat: 0, en: 'He lived there with his wife and their little son, the Boy.', ko: '양치기는 아내, 그리고 어린 아들인 소년과 함께 살았어요.' },
        { beat: 1, en: 'The Boy loved books, and he read about animals and fairy tales every day.', ko: '소년은 책을 무척 좋아해서, 날마다 동물 이야기와 동화를 읽었어요.' },
        { beat: 2, en: 'One evening, the shepherd ran into the house, shaking all over.', ko: '어느 날 저녁, 양치기가 온몸을 덜덜 떨며 집으로 뛰어 들어왔어요.' },
        { beat: 2, en: '"There is something in the cave on the hill!" he cried.', ko: '"언덕 위 동굴에 뭔가가 있어!" 그가 외쳤어요.', bubble: { speaker: 'Father', text: 'Something is in the cave!' } },
        { beat: 3, en: '"I saw it! It is as big as four horses, and it has shiny blue scales!"', ko: '"내가 봤어! 말 네 마리만큼 크고, 반짝이는 파란 비늘이 있어!"' },
        {
          beat: 4, en: 'The Boy closed his book and yawned.', ko: '소년은 책을 덮고 하품을 했어요.',
          action: { kind: 'tap', target: 'book', promptEn: 'Tap the book to close it.', promptKo: '책을 눌러 덮어 봐요.' },
        },
        { beat: 4, en: '"Don\'t worry, Father. It\'s only a dragon," he said.', ko: '"걱정 마세요, 아빠. 그냥 용일 뿐이에요." 소년이 말했어요.', bubble: { speaker: 'Boy', text: "It's only a dragon." } },
        { beat: 4, en: '"Only a dragon?" cried his father. "What do you know about dragons?"', ko: '"그냥 용이라고?" 아빠가 소리쳤어요. "네가 용에 대해 뭘 안다고?"', bubble: { speaker: 'Father', text: 'Only a dragon?!' } },
        { beat: 5, en: '"You know about sheep, and I know about dragons," said the Boy. "Leave it to me."', ko: '"아빠는 양을 잘 알고, 저는 용을 잘 알아요." 소년이 말했어요. "저한테 맡기세요."' },
        { beat: 5, en: 'His mother smiled. "Maybe the poor dragon is lonely up there," she said.', ko: '엄마가 미소 지었어요. "어쩌면 그 불쌍한 용은 저 위에서 외로울지도 몰라." 엄마가 말했어요.', bubble: { speaker: 'Mother', text: 'Maybe he is lonely.' } },
      ],
      words: [
        { word: 'book', ko: '책', hotspot: 'book', beat: 1 },
        { word: 'cave', ko: '동굴', hotspot: 'cave', beat: 1 },
        { word: 'shepherd', ko: '양치기', hotspot: 'father', beat: 2 },
        { word: 'scale', ko: '비늘', hotspot: 'thought', beat: 3 },
      ],
      quiz: {
        question: 'What did the Boy say about the thing in the cave?',
        questionKo: '소년은 동굴 속에 있는 것이 무엇이라고 말했나요?',
        options: ["It's only a dragon.", "It's a big horse.", "It's a giant sheep."],
        answer: 0,
        evidence: 7,
        explainKo: '아빠는 무서워 떨었지만, 책을 많이 읽은 소년은 "그냥 용(dragon)일 뿐이에요"라고 침착하게 말했어요.',
      },
    },
    {
      id: 'hill',
      title: 'Hello, Dragon!',
      titleKo: '안녕, 용아!',
      sentences: [
        { beat: 0, en: 'The next evening, the Boy walked up the white path to the top of the hill.', ko: '다음 날 저녁, 소년은 하얀 길을 따라 언덕 꼭대기까지 걸어 올라갔어요.' },
        { beat: 1, en: 'The view was beautiful. He could see fields, roads, and little houses far below.', ko: '경치가 아름다웠어요. 저 아래로 들판과 길, 작은 집들이 보였어요.' },
        { beat: 1, en: 'A big silver moon was rising in the sky.', ko: '커다란 은빛 달이 하늘로 떠오르고 있었어요.' },
        {
          beat: 2, en: 'And there, in front of the cave, lay the dragon!', ko: '그리고 그곳, 동굴 앞에 용이 누워 있었어요!',
          action: { kind: 'tap', target: 'dragon', promptEn: 'Where is the dragon? Find him and tap!', promptKo: '용은 어디 있을까요? 찾아서 눌러 봐요!' },
        },
        { beat: 2, en: 'He was lying in the grass with his chin on his paws, purring like a happy cat.', ko: '용은 앞발 위에 턱을 괴고 풀밭에 누워서, 기분 좋은 고양이처럼 가르랑거리고 있었어요.' },
        { beat: 2, en: '"Well!" thought the Boy. "My books never said that dragons purr!"', ko: '"이야!" 소년은 생각했어요. "용이 가르랑거린다는 건 어떤 책에도 없었는데!"' },
        { beat: 3, en: '"Hello, dragon!" said the Boy.', ko: '"안녕, 용아!" 소년이 말했어요.', bubble: { speaker: 'Boy', text: 'Hello, dragon!' } },
        { beat: 4, en: 'The dragon looked up and frowned. "Please don\'t hit me or throw stones at me!"', ko: '용이 고개를 들고 얼굴을 찌푸렸어요. "제발 나를 때리거나 돌을 던지지 마!"', bubble: { speaker: 'Dragon', text: "Please don't hit me!" } },
        { beat: 5, en: '"I won\'t hit you," said the Boy, and he sat down in the grass. "I just came to say hello."', ko: '"안 때려." 소년은 이렇게 말하고 풀밭에 앉았어요. "그냥 인사하러 왔어."' },
        { beat: 5, en: '"Oh, how nice!" said the dragon. "I am very happy up here, but it is a little boring sometimes."', ko: '"어머, 반가워라!" 용이 말했어요. "나는 여기서 정말 행복하지만, 가끔은 조금 심심하거든."', bubble: { speaker: 'Dragon', text: 'Oh, how nice!' } },
      ],
      words: [
        { word: 'hill', ko: '언덕', hotspot: 'hill', beat: 0 },
        { word: 'moon', ko: '달', hotspot: 'moon', beat: 1 },
        { word: 'dragon', ko: '용', hotspot: 'dragon', beat: 2 },
        { word: 'paw', ko: '(동물의) 발', hotspot: 'paws', beat: 2 },
      ],
      quiz: {
        question: 'What was the dragon doing when the Boy found him?',
        questionKo: '소년이 용을 찾았을 때 용은 무엇을 하고 있었나요?',
        options: ['Fighting a knight', 'Purring in the grass', 'Flying in the sky'],
        answer: 1,
        evidence: 4,
        explainKo: '용은 앞발에 턱을 괴고 풀밭에 누워 고양이처럼 가르랑거리고(purring) 있었어요. 무서운 괴물과는 전혀 달랐죠!',
      },
    },
    {
      id: 'poems',
      title: 'A Dragon Who Loves Poems',
      titleKo: '시를 좋아하는 용',
      sentences: [
        { beat: 0, en: '"I must tell you a secret," said the dragon. "I am a very lazy dragon."', ko: '"너한테 비밀 하나 말해 줄게." 용이 말했어요. "나는 아주 게으른 용이야."', bubble: { speaker: 'Dragon', text: "I'm a lazy dragon." } },
        { beat: 1, en: '"Other dragons were always busy. They fought, and they chased knights everywhere."', ko: '"다른 용들은 늘 바빴어. 싸우고, 기사들을 쫓아 여기저기 돌아다녔지."' },
        { beat: 2, en: '"But I liked to eat my dinner, lean on a rock, and take a nap."', ko: '"하지만 나는 저녁을 먹고, 바위에 기대서, 낮잠 자는 게 좋았어."' },
        { beat: 3, en: '"One day, the earth shook, and I was stuck deep under the ground."', ko: '"그러던 어느 날 땅이 흔들렸고, 나는 땅속 깊이 갇혀 버렸어."' },
        { beat: 3, en: '"After a long, long time, I dug my way up, and I came out in this cave."', ko: '"아주 아주 오랜 시간이 지나서, 나는 땅을 파고 올라와 이 동굴로 나왔지."' },
        { beat: 4, en: 'Then the dragon\'s face turned a little pink.', ko: '그때 용의 얼굴이 살짝 분홍색이 되었어요.' },
        {
          beat: 4, en: '"Do you ever make up poems?" he asked shyly.', ko: '"너도 시를 지어 본 적 있니?" 용이 수줍게 물었어요.', bubble: { speaker: 'Dragon', text: 'Do you make up poems?' },
          action: { kind: 'feel', target: 'dragon', choices: [ANGRY, SHY, SLEEPY], answer: 1, promptEn: 'Look at his pink face. How does the dragon feel?', promptKo: '분홍색이 된 얼굴을 봐요. 용은 어떤 기분일까요?' },
        },
        { beat: 5, en: '"Yes, lots of them!" said the Boy. And the dragon happily read him a poem about the sunset.', ko: '"응, 아주 많이!" 소년이 대답했어요. 그러자 용은 신이 나서 노을에 관한 시를 읽어 주었어요.' },
        { beat: 6, en: '"That\'s lovely," said the Boy, "but people will think you are a terrible monster!"', ko: '"멋지다." 소년이 말했어요. "그런데 사람들은 네가 무시무시한 괴물이라고 생각할 거야!"', bubble: { speaker: 'Boy', text: "They'll call you a monster!" } },
        { beat: 6, en: '"They will come with spears and swords to fight you!"', ko: '"사람들이 창이랑 칼을 들고 너랑 싸우러 올 거라고!"' },
        { beat: 7, en: '"But I don\'t have a single enemy," said the dragon. "I\'m too lazy to make any!"', ko: '"하지만 나는 적이 하나도 없는걸." 용이 말했어요. "적을 만들기엔 너무 게으르거든!"', bubble: { speaker: 'Dragon', text: 'Too lazy for enemies!' } },
      ],
      words: [
        { word: 'lazy', ko: '게으른', hotspot: 'dragon', beat: 0 },
        { word: 'knight', ko: '기사', hotspot: 'knights', beat: 1 },
        { word: 'rock', ko: '바위', hotspot: 'rock', beat: 2 },
        { word: 'poem', ko: '시', hotspot: 'scroll', beat: 5 },
      ],
      quiz: {
        question: "Why doesn't the dragon have any enemies?",
        questionKo: '용은 왜 적이 하나도 없나요?',
        options: ['He is too lazy to make enemies.', 'He lives on the moon.', 'Everyone is afraid of him.'],
        answer: 0,
        evidence: 10,
        explainKo: '용은 자기가 너무 게을러서(too lazy) 적을 만들 수도 없다고 웃으며 말했어요. 싸움보다 시가 좋은 용이니까요.',
      },
    },
    {
      id: 'village',
      title: 'Talk in the Village',
      titleKo: '마을에 퍼진 소문',
      sentences: [
        { beat: 0, en: 'The Boy told his parents all about his new friend, and the shepherd came to meet him.', ko: '소년은 부모님께 새 친구 이야기를 모두 들려주었고, 양치기 아빠도 용을 만나러 왔어요.' },
        { beat: 0, en: 'His mother sent up warm food, but she was still a little shy of the big dragon.', ko: '엄마는 따뜻한 음식을 보내 주었지만, 커다란 용 앞에서는 아직 조금 쑥스러워했어요.' },
        { beat: 1, en: 'Every evening, the Boy sat with the dragon and listened to stories about the old days.', ko: '저녁마다 소년은 용 곁에 앉아 옛날이야기를 들었어요.' },
        { beat: 2, en: 'But a dragon as big as four horses cannot hide for long.', ko: '하지만 말 네 마리만큼 큰 용이 오래 숨어 있을 수는 없었어요.' },
        { beat: 2, en: 'Soon, everyone in the village was talking about the dragon in the cave.', ko: '곧 마을 사람 모두가 동굴 속 용 이야기를 하게 되었어요.' },
        { beat: 3, en: 'The people were scared, but they were also a little proud.', ko: '사람들은 무서워했지만, 한편으로는 조금 자랑스러워하기도 했어요.' },
        { beat: 4, en: '"A dragon is a dragon! He must go!" they shouted.', ko: '"용은 용이야! 쫓아내야 해!" 사람들이 소리쳤어요.', bubble: { speaker: 'Villagers', text: 'He must go!' } },
        {
          beat: 5, en: 'But the dragon had never hurt anyone, not even a single chicken.', ko: '하지만 용은 누구도 다치게 한 적이 없었어요. 닭 한 마리조차도요.',
          action: { kind: 'tap', target: 'henhouse', promptEn: 'Did the dragon hurt anyone? Tap the hen house.', promptKo: '용이 누굴 다치게 했을까요? 닭장을 눌러 확인해요.' },
        },
        { beat: 6, en: 'And nobody in the village was brave enough to fight him.', ko: '그리고 마을에는 용과 싸울 만큼 용감한 사람이 아무도 없었어요.' },
        { beat: 7, en: 'Meanwhile, up on the hill, the dragon watched the sunset and wrote new poems.', ko: '그동안 언덕 위의 용은 노을을 바라보며 새로운 시를 썼어요.' },
      ],
      words: [
        { word: 'village', ko: '마을', hotspot: 'village', beat: 2 },
        { word: 'chicken', ko: '닭', hotspot: 'henhouse', beat: 5 },
        { word: 'brave', ko: '용감한', hotspot: 'villagers', beat: 6 },
        { word: 'sunset', ko: '노을, 해 질 녘', hotspot: 'sun', beat: 7 },
      ],
      quiz: {
        question: 'Had the dragon hurt anyone in the village?',
        questionKo: '용은 마을에서 누군가를 다치게 한 적이 있나요?',
        options: ['Yes, many people.', 'No, not even a chicken.', 'Only the shepherd.'],
        answer: 1,
        evidence: 7,
        explainKo: '사람들은 용을 쫓아내야 한다고 했지만, 용은 닭(chicken) 한 마리도 다치게 한 적이 없었어요.',
      },
    },
    {
      id: 'george',
      title: 'The Knight Is Coming!',
      titleKo: '기사가 온다!',
      sentences: [
        { beat: 0, en: 'One morning, the village looked like a big party.', ko: '어느 날 아침, 마을은 커다란 잔치처럼 꾸며져 있었어요.' },
        {
          beat: 0, en: 'Bright flags hung from the windows, flowers covered the street, and the bells rang and rang.', ko: '창문마다 알록달록한 깃발이 걸리고, 거리는 꽃으로 덮였고, 종이 계속 울렸어요.',
          action: { kind: 'tap', target: 'bell', count: 3, promptEn: 'Ring the bell! Tap it three times.', promptKo: '종을 세 번 눌러 울려 봐요!' },
        },
        { beat: 1, en: '"What\'s happening?" asked the Boy. "St. George is coming!" shouted his friend.', ko: '"무슨 일이야?" 소년이 물었어요. "성 조지가 온대!" 친구가 소리쳤어요.', bubble: { speaker: 'Friend', text: 'St. George is coming!' } },
        { beat: 1, en: '"He will fight our dragon! What a great fight it will be!"', ko: '"그분이 우리 용이랑 싸울 거래! 정말 굉장한 싸움이 될 거야!"' },
        { beat: 2, en: 'Then a tall white horse came slowly down the street.', ko: '그때 키 큰 흰 말이 천천히 거리를 걸어왔어요.' },
        { beat: 2, en: 'On it sat St. George in shining golden armor, with a long, long spear.', ko: '그 위에는 번쩍이는 황금 갑옷을 입고 아주 긴 창을 든 성 조지가 앉아 있었어요.' },
        { beat: 3, en: 'Everyone cheered. "Don\'t worry," he said kindly. "I will free you from the dragon."', ko: '모두가 환호했어요. "걱정 마세요." 그가 다정하게 말했어요. "내가 용에게서 여러분을 구해 주겠소."', bubble: { speaker: 'St. George', text: 'I will free you!' } },
        { beat: 4, en: 'But the Boy ran up the hill as fast as he could.', ko: '하지만 소년은 있는 힘껏 언덕 위로 달려갔어요.' },
        { beat: 5, en: 'The dragon was polishing his scales with an old cloth from the Boy\'s mother.', ko: '용은 소년의 엄마가 준 낡은 천으로 비늘을 닦고 있었어요.' },
        {
          beat: 6, en: 'He shone like a big blue jewel.', ko: '용은 커다란 파란 보석처럼 반짝였어요.',
          action: { kind: 'rub', target: 'dragon', promptEn: 'Help the dragon shine! Rub his scales.', promptKo: '용의 비늘을 문질러 반짝반짝 닦아 줘요!' },
        },
        { beat: 6, en: '"Don\'t shout, Boy," he said calmly. "Sit down and tell me who is coming."', ko: '"소리 지르지 마렴." 용이 차분하게 말했어요. "앉아서 누가 온다는 건지 말해 봐."', bubble: { speaker: 'Dragon', text: 'Who is coming?' } },
      ],
      words: [
        { word: 'flag', ko: '깃발', hotspot: 'flags', beat: 0 },
        { word: 'bell', ko: '종', hotspot: 'bell', beat: 0 },
        { word: 'horse', ko: '말', hotspot: 'horse', beat: 2 },
        { word: 'armor', ko: '갑옷', hotspot: 'george', beat: 2 },
      ],
      quiz: {
        question: 'Why did St. George come to the village?',
        questionKo: '성 조지는 왜 마을에 왔나요?',
        options: ['To fight the dragon', 'To buy flowers', 'To visit the Boy'],
        answer: 0,
        evidence: 3,
        explainKo: '마을 사람들은 성 조지가 용과 싸우러(fight) 왔다고 신이 났어요. 그래서 소년은 급히 용에게 달려갔죠.',
      },
    },
    {
      id: 'refuse',
      title: "I Won't Fight!",
      titleKo: '나는 안 싸울 거야!',
      sentences: [
        { beat: 0, en: '"St. George is here! He has the longest spear you ever saw!" said the Boy.', ko: '"성 조지가 왔어! 네가 본 것 중에 제일 긴 창을 가지고 있어!" 소년이 말했어요.', bubble: { speaker: 'Boy', text: 'St. George is here!' } },
        { beat: 0, en: 'The Boy jumped up and down. He really wanted to see a big fight.', ko: '소년은 폴짝폴짝 뛰었어요. 커다란 싸움이 정말 보고 싶었거든요.' },
        { beat: 1, en: '"Oh dear, oh dear!" cried the dragon. "This is terrible!"', ko: '"아이고, 이를 어째!" 용이 외쳤어요. "큰일 났네!"', bubble: { speaker: 'Dragon', text: 'Oh dear, oh dear!' } },
        {
          beat: 2, en: '"I won\'t see him. Please tell him to go away!"', ko: '"나는 그 사람 안 만날 거야. 제발 돌아가라고 말해 줘!"',
          action: { kind: 'feel', target: 'dragon', choices: [EXCITED, WORRIED, ANGRY], answer: 1, promptEn: 'Look at the dragon. How does he feel?', promptKo: '용의 얼굴을 봐요. 용은 어떤 기분일까요?' },
        },
        { beat: 3, en: '"But you have to fight him," said the Boy. "He is St. George, and you are the dragon!"', ko: '"그래도 싸워야 해." 소년이 말했어요. "그는 성 조지고, 너는 용이잖아!"' },
        { beat: 3, en: '"My dear little friend," said the dragon, "I can\'t fight, and I won\'t fight."', ko: '"귀여운 내 친구야." 용이 말했어요. "나는 싸울 줄도 모르고, 싸우지도 않을 거야."', bubble: { speaker: 'Dragon', text: "I won't fight!" } },
        { beat: 3, en: '"I have never fought anyone in my whole life."', ko: '"나는 평생 누구와도 싸워 본 적이 없거든."' },
        { beat: 4, en: '"But if you don\'t fight, he will cut off your head!" cried the Boy.', ko: '"하지만 안 싸우면, 그가 네 머리를 베어 버릴 거야!" 소년이 울먹였어요.' },
        { beat: 5, en: '"Oh, I don\'t think so," said the dragon lazily. "You are clever. You will think of something."', ko: '"에이, 그렇진 않을걸." 용이 느긋하게 말했어요. "너는 똑똑하잖아. 무슨 방법을 생각해 낼 거야."', bubble: { speaker: 'Dragon', text: "You'll think of something!" } },
        { beat: 6, en: 'So the Boy walked slowly back down the hill. He felt very worried.', ko: '그래서 소년은 터벅터벅 언덕을 내려갔어요. 소년은 무척 걱정이 되었어요.' },
      ],
      words: [
        { word: 'jump', ko: '뛰다', hotspot: 'boy', beat: 0 },
        { word: 'fight', ko: '싸우다', hotspot: 'dragon', beat: 3 },
        { word: 'clever', ko: '똑똑한', hotspot: 'boy', beat: 5 },
        { word: 'worried', ko: '걱정하는', hotspot: 'boy', beat: 6 },
      ],
      quiz: {
        question: 'What did the dragon say about fighting?',
        questionKo: '용은 싸움에 대해 뭐라고 말했나요?',
        options: ['"I love to fight!"', '"I can\'t fight, and I won\'t fight."', '"I will fight tomorrow."'],
        answer: 1,
        evidence: 5,
        explainKo: '용은 "I can\'t fight, and I won\'t fight(싸울 줄도 모르고, 싸우지도 않을 거야)"라고 했어요. 평생 한 번도 싸운 적이 없는 용이거든요.',
      },
    },
    {
      id: 'inn',
      title: 'The Boy and the Knight',
      titleKo: '소년과 기사',
      sentences: [
        { beat: 0, en: 'Down in the village, everyone was happily talking about the big fight.', ko: '마을에서는 모두가 신이 나서 큰 싸움 이야기를 하고 있었어요.' },
        { beat: 1, en: 'The Boy went to the inn, where St. George was sitting all alone.', ko: '소년은 성 조지가 혼자 앉아 있는 여관으로 갔어요.' },
        {
          beat: 2, en: 'Knock, knock! "May I come in, St. George? I want to talk about the dragon."', ko: '똑똑! "들어가도 될까요, 성 조지 님? 용에 대해 드릴 말씀이 있어요."', bubble: { speaker: 'Boy', text: 'May I come in?' },
          action: { kind: 'tap', target: 'door', count: 2, promptEn: 'Knock on the door! Tap it two times.', promptKo: '문을 두 번 눌러 똑똑 두드려요!' },
        },
        { beat: 3, en: '"Come in, Boy," said the knight kindly. "Did the dragon hurt your family?"', ko: '"들어오너라." 기사가 다정하게 말했어요. "용이 네 가족을 해쳤니?"' },
        { beat: 4, en: '"No! That\'s the problem," said the Boy. "He is a good dragon, and he is my friend."', ko: '"아니요! 그게 문제예요." 소년이 말했어요. "그 용은 착한 용이고, 제 친구예요."', bubble: { speaker: 'Boy', text: 'He is a good dragon!' } },
        { beat: 4, en: '"He tells wonderful stories, and he is very kind to my mother."', ko: '"멋진 이야기를 들려주고, 우리 엄마한테도 아주 친절해요."' },
        { beat: 5, en: '"The people here tell lots of tall tales. They just want to see a fight!"', ko: '"여기 사람들은 과장된 이야기를 많이 해요. 그냥 싸움 구경이 하고 싶은 거예요!"' },
        { beat: 6, en: 'St. George thought for a long time. "Maybe I was wrong about the dragon," he said.', ko: '성 조지는 한참 동안 생각했어요. "내가 용을 잘못 알았는지도 모르겠구나." 그가 말했어요.', bubble: { speaker: 'St. George', text: 'Maybe I was wrong.' } },
        { beat: 6, en: '"But what can we do? Can you think of a plan?"', ko: '"그런데 어떻게 하면 좋을까? 너에게 좋은 계획이 있니?"' },
        { beat: 7, en: '"Come up the hill with me and meet him," said the Boy.', ko: '"저랑 같이 언덕에 올라가서 용을 만나 보세요." 소년이 말했어요.' },
        { beat: 8, en: '"Cheer up," said St. George. "Maybe there won\'t be any fight after all."', ko: '"힘내렴." 성 조지가 말했어요. "어쩌면 싸움은 아예 없을지도 몰라."' },
        { beat: 8, en: '"Oh, but I hope there will be!" said the Boy with a grin.', ko: '"에이, 그래도 싸움은 있었으면 좋겠는데요!" 소년이 씩 웃으며 말했어요.', bubble: { speaker: 'Boy', text: 'I hope there will be!' } },
      ],
      words: [
        { word: 'inn', ko: '여관', hotspot: 'inn', beat: 1 },
        { word: 'knock', ko: '(문을) 두드리다', hotspot: 'door', beat: 1 },
        { word: 'friend', ko: '친구', hotspot: 'boy', beat: 4 },
        { word: 'plan', ko: '계획', hotspot: 'george', beat: 6 },
      ],
      quiz: {
        question: 'What did the Boy tell St. George about the dragon?',
        questionKo: '소년은 성 조지에게 용에 대해 뭐라고 말했나요?',
        options: ['He is a good dragon and my friend.', 'He eats sheep every day.', 'He is hiding a princess.'],
        answer: 0,
        evidence: 4,
        explainKo: '소년은 용이 착한 용(a good dragon)이고 자기 친구라고 용감하게 말했어요. 그 말을 듣고 성 조지도 다시 생각하게 되었죠.',
      },
    },
    {
      id: 'plan',
      title: 'A Secret Plan',
      titleKo: '비밀 계획',
      sentences: [
        { beat: 0, en: 'That night, the Boy brought St. George up the hill to meet the dragon.', ko: '그날 밤, 소년은 용을 만나게 해 주려고 성 조지를 데리고 언덕에 올라갔어요.' },
        { beat: 1, en: '"Nice to meet you, sir!" said the dragon politely. "Lovely weather tonight!"', ko: '"만나서 반갑습니다!" 용이 공손하게 말했어요. "오늘 밤 날씨가 참 좋네요!"', bubble: { speaker: 'Dragon', text: 'Nice to meet you!' } },
        { beat: 2, en: '"Shall we just have a fight by the rules?" asked St. George.', ko: '"그냥 규칙대로 한판 싸워 볼까?" 성 조지가 물었어요.' },
        { beat: 2, en: '"No, thank you," said the dragon. "If you make me, I will just hide in my cave."', ko: '"아뇨, 괜찮습니다." 용이 말했어요. "억지로 싸우라고 하면, 저는 그냥 동굴에 숨어 버릴 거예요."', bubble: { speaker: 'Dragon', text: 'No, thank you!' } },
        { beat: 3, en: '"But this hill is a perfect place for a fight," said the knight.', ko: '"하지만 이 언덕은 싸우기에 딱 좋은 곳인걸." 기사가 말했어요.' },
        { beat: 3, en: '"Think of it! My golden armor and your blue scales. What a beautiful picture!"', ko: '"생각해 봐! 나의 황금 갑옷과 너의 파란 비늘. 얼마나 멋진 그림이겠니!"' },
        { beat: 4, en: '"Hmm, it would be a pretty picture," said the dragon slowly.', ko: '"음, 멋진 그림이긴 하겠네요." 용이 천천히 말했어요.' },
        { beat: 5, en: '"I must touch you with my spear, but I don\'t need to hurt you," said St. George.', ko: '"창으로 너를 건드리긴 해야 하지만, 다치게 할 필요는 없지." 성 조지가 말했어요.' },
        { beat: 6, en: '"How about behind your front leg?" "Hee hee! No, that tickles!" laughed the dragon.', ko: '"앞다리 뒤쪽은 어때?" "히히! 안 돼요, 간지러워요!" 용이 웃었어요.', bubble: { speaker: 'Dragon', text: 'Hee hee! That tickles!' } },
        {
          beat: 7, en: '"Then under your neck, in these thick, soft folds of skin. You won\'t feel a thing."', ko: '"그럼 목 아래, 두툼하고 말랑한 피부 주름은 어때? 하나도 안 느껴질 거야."',
          action: { kind: 'tap', target: 'neck', promptEn: 'Find a safe spot! Tap the soft folds under his neck.', promptKo: '안전한 곳을 찾아요! 용의 목 아래 말랑한 주름을 눌러요.' },
        },
        { beat: 8, en: '"And after the fight?" asked the dragon. "Then we will all have a big feast," said the knight.', ko: '"싸움이 끝나면요?" 용이 물었어요. "그다음엔 다 함께 큰 잔치를 열지." 기사가 말했어요.' },
        { beat: 9, en: '"A feast? Wonderful!" said the dragon. "Then it\'s a deal!"', ko: '"잔치요? 좋아요!" 용이 말했어요. "그럼 약속한 거예요!"', bubble: { speaker: 'Dragon', text: "It's a deal!" } },
      ],
      words: [
        { word: 'rule', ko: '규칙', hotspot: 'george', beat: 2 },
        { word: 'picture', ko: '그림', hotspot: 'picture', beat: 3 },
        { word: 'neck', ko: '목', hotspot: 'neck', beat: 7 },
        { word: 'feast', ko: '잔치', hotspot: 'feast', beat: 8 },
      ],
      quiz: {
        question: "Where will St. George's spear touch the dragon?",
        questionKo: '성 조지의 창은 용의 어디를 건드리기로 했나요?',
        options: ['On his nose', 'Behind his front leg', 'In the soft folds under his neck'],
        answer: 2,
        evidence: 9,
        explainKo: '앞다리 뒤쪽은 간지러워서 안 됐어요. 그래서 하나도 아프지 않은 목 아래 피부 주름(folds under his neck)으로 정했죠.',
      },
    },
    {
      id: 'show',
      title: 'The Big Show',
      titleKo: '멋진 한판 승부',
      sentences: [
        { beat: 0, en: 'The next morning, the whole village climbed the hill in their best clothes.', ko: '다음 날 아침, 온 마을 사람들이 가장 좋은 옷을 입고 언덕을 올라왔어요.' },
        { beat: 0, en: 'They carried baskets of food and found good places on the grass.', ko: '사람들은 음식 바구니를 들고 와서 풀밭에 좋은 자리를 잡았어요.' },
        { beat: 1, en: 'The Boy sat right at the front. Would the dragon really come out?', ko: '소년은 맨 앞에 앉았어요. 용이 정말 나와 줄까요?' },
        { beat: 2, en: 'Then St. George rode up the hill, his golden armor shining in the sun.', ko: '그때 성 조지가 황금 갑옷을 햇빛에 반짝이며 말을 타고 올라왔어요.' },
        {
          beat: 3, en: 'Suddenly, there was a loud roar, and smoke filled the mouth of the cave.', ko: '갑자기 커다란 울부짖음이 들리더니, 동굴 입구가 연기로 가득 찼어요.',
          action: { kind: 'hold', target: 'cave', promptEn: 'Press and hold the cave to call the dragon out!', promptKo: '동굴을 길게 눌러 용을 불러내요!' },
        },
        { beat: 4, en: 'Out pranced the dragon, blue and shining, with fire coming from his nose!', ko: '파랗게 반짝이는 용이 코에서 불을 뿜으며 껑충껑충 뛰어나왔어요!' },
        { beat: 4, en: '"Ooooh!" said everyone.', ko: '"우와아!" 모두가 감탄했어요.', bubble: { speaker: 'Everyone', text: 'Ooooh!' } },
        { beat: 5, en: 'In round one, St. George charged with his spear, but he missed!', ko: '첫 번째 판에서 성 조지가 창을 들고 돌진했지만, 빗나갔어요!' },
        { beat: 6, en: 'In round two, the dragon jumped from side to side, and the horse ran away in fright.', ko: '두 번째 판에서는 용이 이리저리 펄쩍펄쩍 뛰자, 말이 깜짝 놀라 달아나 버렸어요.' },
        { beat: 7, en: 'The people cheered for the dragon, and he proudly puffed out his chest.', ko: '사람들이 용을 응원했고, 용은 자랑스럽게 가슴을 쭉 폈어요.' },
        { beat: 8, en: 'In round three, St. George moved like lightning.', ko: '세 번째 판에서 성 조지는 번개처럼 움직였어요.' },
        { beat: 9, en: 'The spear went into the soft folds under the dragon\'s neck, and he fell to the ground.', ko: '창이 용의 목 아래 말랑한 주름에 쏙 들어갔고, 용은 땅에 쓰러졌어요.' },
        { beat: 10, en: 'The Boy ran to him, but the dragon opened one eye and gave him a big wink.', ko: '소년이 달려갔지만, 용은 한쪽 눈을 뜨고 소년에게 찡긋 윙크를 했어요.' },
      ],
      words: [
        { word: 'basket', ko: '바구니', hotspot: 'baskets', beat: 0 },
        { word: 'smoke', ko: '연기', hotspot: 'cave', beat: 3 },
        { word: 'fire', ko: '불', hotspot: 'dragon', beat: 4 },
        { word: 'wink', ko: '윙크(하다)', hotspot: 'dragon', beat: 10 },
      ],
      quiz: {
        question: 'Why did the dragon wink at the Boy?',
        questionKo: '용은 왜 소년에게 윙크를 했나요?',
        options: ['He was really hurt.', 'He was fine. It was all part of the plan.', 'He had dust in his eye.'],
        answer: 1,
        evidence: 12,
        explainKo: '창은 약속한 피부 주름에 들어가서 용은 하나도 다치지 않았어요. 윙크(wink)는 "다 계획대로야!"라는 신호였죠.',
      },
    },
    {
      id: 'feast',
      title: 'Friends at Last',
      titleKo: '모두가 친구',
      sentences: [
        { beat: 0, en: '"Aren\'t you going to cut off his head?" asked a man in the crowd.', ko: '"용의 머리를 베지 않을 건가요?" 구경꾼 중 한 남자가 물었어요.' },
        { beat: 0, en: '"Not today," said St. George with a smile. "Let\'s all go down and eat first."', ko: '"오늘은 아니오." 성 조지가 웃으며 말했어요. "먼저 다 같이 내려가서 밥부터 먹읍시다."', bubble: { speaker: 'St. George', text: 'Not today!' } },
        { beat: 1, en: 'So everyone marched down to the village, with the dragon walking next to the Boy.', ko: '그래서 모두가 마을로 행진해 내려갔고, 용은 소년 옆에서 함께 걸었어요.' },
        { beat: 2, en: 'St. George made a speech. "The dragon is good now, and he wants to be your friend."', ko: '성 조지가 연설을 했어요. "이제 용은 착해졌고, 여러분과 친구가 되고 싶어 합니다."', bubble: { speaker: 'St. George', text: "Let's all be friends!" } },
        { beat: 2, en: '"Don\'t love fights so much, and don\'t make up scary stories!"', ko: '"싸움을 너무 좋아하지 말고, 무서운 이야기를 지어내지도 마세요!"' },
        { beat: 3, en: 'Then there was a wonderful feast, and the dragon was the star of the party.', ko: '그다음엔 멋진 잔치가 열렸고, 용은 잔치의 주인공이 되었어요.' },
        { beat: 3, en: 'Everyone loved his stories, his jokes, and even his poems.', ko: '모두가 용의 이야기와 농담, 그리고 시까지 좋아했어요.' },
        { beat: 4, en: 'Late that night, the dragon sat down in the road and fell asleep.', ko: '그날 밤늦게, 용은 길바닥에 털썩 앉더니 잠들어 버렸어요.' },
        { beat: 4, en: '"Wake up, dragon!" cried the tired Boy. "You promised I would walk you home!"', ko: '"일어나, 용아!" 지친 소년이 울먹였어요. "내가 집까지 데려다주기로 약속했잖아!"', bubble: { speaker: 'Boy', text: 'Wake up, dragon!' } },
        { beat: 5, en: 'St. George came out and helped. "Wake up, dragon! This little boy needs to go to bed!"', ko: '성 조지가 나와서 도와주었어요. "일어나거라, 용아! 이 꼬마는 이제 자러 가야 한단다!"' },
        {
          beat: 6, en: 'The dragon jumped up. "Oh, poor little boy! Let\'s go home right now!"', ko: '용이 벌떡 일어났어요. "어머, 불쌍한 꼬마야! 지금 당장 집에 가자!"', bubble: { speaker: 'Dragon', text: "Let's go home!" },
          action: { kind: 'tap', target: 'dragon', count: 3, promptEn: 'Help wake the dragon! Tap him three times.', promptKo: '용을 깨워 줘요! 용을 세 번 눌러요.' },
        },
        { beat: 7, en: 'So the knight, the dragon, and the Boy walked up the hill together, arm in arm, under the stars.', ko: '그렇게 기사와 용과 소년은 별빛 아래 팔짱을 끼고 함께 언덕을 올라갔어요.' },
        { beat: 7, en: 'And as they went, someone sang a happy old song. I think it was the dragon!', ko: '그리고 걸어가는 동안 누군가 즐거운 옛 노래를 불렀어요. 아마 용이었을 거예요!' },
      ],
      words: [
        { word: 'speech', ko: '연설', hotspot: 'george', beat: 2 },
        { word: 'feast', ko: '잔치', hotspot: 'table', beat: 3 },
        { word: 'asleep', ko: '잠든', hotspot: 'dragon', beat: 4 },
        { word: 'song', ko: '노래', hotspot: 'dragon', beat: 7 },
      ],
      quiz: {
        question: 'How did the story end?',
        questionKo: '이야기는 어떻게 끝났나요?',
        options: ['The dragon flew far away.', 'The three friends walked home together.', 'St. George went to fight another dragon.'],
        answer: 1,
        evidence: 11,
        explainKo: '기사와 용과 소년, 세 친구는 별빛 아래 팔짱을 끼고(arm in arm) 함께 언덕을 올라갔어요. 아무도 다치지 않은 행복한 결말이에요.',
      },
    },
  ],
};
